# RBAC for fence-controller pod
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fence-controller
  namespace: default
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
      - configmaps
      - pods
      - events
    verbs:
      - "*"
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
  - apiGroups:
      - ha.k8s.io
    resources:
      - nodefences
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fence-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fence-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: fence-controller
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fence-controller
    namespace: default
---
# custom resource definitions
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodefences.v1.ha.k8s.io
spec:
  group: v1.ha.k8s.io
  version: v1
  scope: Namespaced
  names:
    plural: nodefences
    singular: nodefence
    kind: NodeFence
---
# kubevirt controller
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fence-controller
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: standalone-fence-controller
    spec:
      serviceAccountName: fence-controller
      containers:
        - name: standalone-fence-controller
          image: "registry.hub.docker.com/nodefencing/standalone-fence-controller:latest"
          imagePullPolicy: Always
---
# RBAC for fence agent pod
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fence-agent
  namespace: default
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
      - nodes
      - pods
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fence-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fence-agent
  namespace: default
roleRef:
  kind: ClusterRole
  name: fence-agent
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fence-agent
    namespace: default
---

